# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  flake.modules.nixos.OmnisonHardware = { config, lib, pkgs, modulesPath, ... }:{
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.initrd.luks.devices."cryptnixos" = {
        device = "/dev/disk/by-uuid/f16fba76-a92b-4db0-806a-c04e663819f3";
    };

    boot.initrd.luks.devices."crypthome" = {
        device = "/dev/disk/by-uuid/fc27aa46-9925-4277-979e-564e4703d73e";
        keyFile = "/cryptkey";
    };

    boot.initrd.secrets."/cryptkey" = builtins.path {
        path = "/secrets/cryptkey";
        name = "cryptkey";
    };

    fileSystems."/home/azex/Documents" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=Documents,compress=zstd" ];
    };

    fileSystems."/home/azex/IT" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=IT,compress=zstd" ];
    };

    fileSystems."/home/azex/College" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=College,compress=zstd" ];
    };

    fileSystems."/home/azex/Pictures" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=Pictures" ];
    };

    fileSystems."/home/azex/Videos" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=Videos" ];
    };

    fileSystems."/home/azex/Music" = {
        device = "/dev/mapper/crypthome";
        fsType = "btrfs";
        options = [ "subvol=Music" ];
    };


    fileSystems."/" =
      { device = "/dev/mapper/cryptnixos";
        fsType = "btrfs";
      };

    fileSystems."/home" =
      { device = "/dev/mapper/cryptnixos";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };

    fileSystems."/nix" =
      { device = "/dev/mapper/cryptnixos";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/4FCC-F034";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ {
      device = "/var/lib/swapfile";
      size = 8*1024; # 8 GiB
    } ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.npu.enable = true;
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
